"""Flet 图标常量 (字符串形式，兼容各版本 Flet)

使用字符串形式避免 ft.icons.XXX 在模块加载时的兼容性问题
"""

# 导航图标
RADAR = "radar"
ACCOUNT_CIRCLE = "account_circle"
ACCOUNT_CIRCLE_OUTLINED = "account_circle_outlined"
VPN_LOCK = "vpn_lock"
VPN_LOCK_OUTLINED = "vpn_lock_outlined"
BOLT = "bolt"
BOLT_OUTLINED = "bolt_outlined"
FORUM = "forum"
FORUM_OUTLINED = "forum_outlined"
TRAVEL_EXPLORE = "travel_explore"
TRAVEL_EXPLORE_OUTLINED = "travel_explore_outlined"
SHIELD = "shield"
SHIELD_OUTLINED = "shield_outlined"
SEND = "send"
SEND_ROUNDED = "send_rounded"
EXTENSION = "extension"
EXTENSION_OUTLINED = "extension_outlined"
SETTINGS = "settings"
SETTINGS_OUTLINED = "settings_outlined"

# 操作图标
PLAY_ARROW = "play_arrow"
PLAY_ARROW_ROUNDED = "play_arrow_rounded"
PLAY_CIRCLE_FILL_ROUNDED = "play_circle_fill_rounded"
STOP_CIRCLE_ROUNDED = "stop_circle_rounded"
CHECK = "check"
CHECK_CIRCLE = "check_circle"
CHECK_CIRCLE_ROUNDED = "check_circle_rounded"
ERROR = "error"
ERROR_OUTLINE = "error_outline"
WARNING = "warning"
WARNING_AMBER = "warning_amber"
WARNING_AMBER_ROUNDED = "warning_amber_rounded"
INFO = "info"

# 功能图标
ADD = "add"
ADD_BOX = "add_box"
ADD_LINK_ROUNDED = "add_link_rounded"
ADD_TO_PHOTOS = "add_to_photos"
APPS = "apps"
ARCHIVE_ROUNDED = "archive_rounded"
ARROW_BACK_IOS_NEW = "arrow_back_ios_new"
AUTO_AWESOME = "auto_awesome"
AUTO_AWESOME_MOTION_ROUNDED = "auto_awesome_motion_rounded"
BOLT = "bolt"
COPY_ALL = "copy_all"
DELETE = "delete"
DELETE_FOREVER = "delete_forever"
DELETE_FOREVER_OUTLINED = "delete_forever_outlined"
DELETE_OUTLINE = "delete_outline"
DELETE_SWEEP = "delete_sweep"
DELETE_SWEEP_OUTLINED = "delete_sweep_outlined"
EDIT_DOCUMENT = "edit_document"
EDIT_NOTE_ROUNDED = "edit_note_rounded"
FILE_OPEN = "file_open"
HISTORY = "history"
HISTORY_ROUNDED = "history_rounded"
HTTP = "http"
KEYBOARD = "keyboard"
LINK_ROUNDED = "link_rounded"
LIST_ALT_ROUNDED = "list_alt_rounded"
LOGIN_ROUNDED = "login_rounded"
MEMORY_ROUNDED = "memory_rounded"
NETWORK_CHECK = "network_check"
NEW_RELEASES = "new_releases"
OPEN_IN_NEW = "open_in_new"
PERSON = "person"
PERSON_ADD_ROUNDED = "person_add_rounded"
PERSON_SEARCH = "person_search"
POST_ADD = "post_add"
POWER_SETTINGS_NEW_ROUNDED = "power_settings_new_rounded"
PUBLIC = "public"
REFRESH_ROUNDED = "refresh_rounded"
RESTORE_PAGE = "restore_page"
RULE_ROUNDED = "rule_rounded"
SAVE = "save"
SAVE_ROUNDED = "save_rounded"
SCHEDULE = "schedule"
SCHEDULE_ROUNDED = "schedule_rounded"
SEARCH = "search"
SECURITY = "security"
SENSORS = "sensors"
SHADOWS = "shadows"
SPEED = "speed"
SPEED_ROUNDED = "speed_rounded"
STREAM_ROUNDED = "stream_rounded"
SYNC_PROBLEM_ROUNDED = "sync_problem_rounded"
SYNC_ROUNDED = "sync_rounded"
TERMINAL = "terminal"
TIMER_OUTLINED = "timer_outlined"
TOUCH_APP_ROUNDED = "touch_app_rounded"
UNDO = "undo"
UPDATE_ROUNDED = "update_rounded"
VERIFIED_USER = "verified_user"
VPN_KEY_ROUNDED = "vpn_key_rounded"
WIFI_TETHERING_ROUNDED = "wifi_tethering_rounded"

# 通知相关
NOTIFICATIONS = "notifications"
NOTIFICATIONS_NONE = "notifications_none"
NOTIFICATIONS_OUTLINED = "notifications_outlined"

# 特殊图标
HELP_OUTLINE = "help_outline"
LOCAL_FIRE_DEPARTMENT_ROUNDED = "local_fire_department_rounded"
RADIO_BUTTON_CHECKED = "radio_button_checked"
SELECT_ALL = "select_all"

# 模式切换 / 用户图标 (sign.py)
GROUP_WORK = "group_work"
PERSON = "person"
SWAP_HORIZ = "swap_horiz"
SYNC_ROUNDED = "sync_rounded"
PLAY_ARROW_ROUNDED = "play_arrow_rounded"
ACCESS_TIME_ROUNDED = "access_time_rounded"

# 授权 / 安全图标 (settings.py)
GPP_GOOD_ROUNDED = "gpp_good_rounded"
WIFI_TETHERING_ROUNDED = "wifi_tethering_rounded"
LOGIN_ROUNDED = "login_rounded"

# 规则管理图标 (rules.py)
NO_ENCRYPTION_ROUNDED = "no_encryption_rounded"
TERMINAL = "terminal"
KEYBOARD = "keyboard"
CHECK = "check"

# 代理管理图标 (proxy.py)
ADD_LINK_ROUNDED = "add_link_rounded"
SPEED = "speed"
DELETE_SWEEP = "delete_sweep"
LINK_OFF = "link_off"
HTTP = "http"
SPEED_ROUNDED = "speed_rounded"
LINK_OFF = "link_off"

# 仪表盘导航图标 (dashboard.py)
EDIT_NOTE_ROUNDED = "edit_note_rounded"
OPEN_IN_NEW = "open_in_new"
AUTO_AWESOME = "auto_awesome"
